#ifndef MAT_GEN_H_INCLUDED
#define MAT_GEN_H_INCLUDED

extern void mat(int n);//this function makes use of the memoryalloc.h module//

extern int* matrix_s(int n);//this function makes all the elements 1 except for the matrix borders that will be 0//

extern void path_an(int x,int y);//this function analyses the possibility of a path to be
                                 //generated by the algorithm in a certain direction//

extern int whtogo(int N,int V,int S,int E);//this function puts the possible path development directions into a vector as numbers

extern void mov_arb(int s);//this function changes the matrix elements into 0 when the path is generated//

extern int* gen_mat(int dim);//in this function all the previous ones are used and linked together//

#endif // MAT_GEN_H_INCLUDED
